/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    rooms: Room;
    dining: Dining;
    facilities: Facility;
    events: Event;
    offers: Offer;
    galleries: Gallery;
    posts: Post;
    bookings: Booking;
    reviews: Review;
    destinations: Destination;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    dining: DiningSelect<false> | DiningSelect<true>;
    facilities: FacilitiesSelect<false> | FacilitiesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    offers: OffersSelect<false> | OffersSelect<true>;
    galleries: GalleriesSelect<false> | GalleriesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('id' | 'en') | ('id' | 'en')[];
  globals: {
    'home-page': HomePage;
    'site-settings': SiteSetting;
    'header-config': HeaderConfig;
    'footer-config': FooterConfig;
    popups: Popup;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'header-config': HeaderConfigSelect<false> | HeaderConfigSelect<true>;
    'footer-config': FooterConfigSelect<false> | FooterConfigSelect<true>;
    popups: PopupsSelect<false> | PopupsSelect<true>;
  };
  locale: 'id' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role: 'admin' | 'editor' | 'reservations';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  name: string;
  slug: string;
  category: 'superior' | 'executive' | 'royal-suite' | 'family-suite';
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  size: number;
  bedType: string;
  capacity: number;
  order?: number | null;
  basePrice: number;
  discountPrice?: number | null;
  featuredImage?: (number | null) | Media;
  imageUrl?: string | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  amenities?:
    | {
        name: string;
        icon?:
          | (
              | 'wifi'
              | 'bed'
              | 'tv'
              | 'air-conditioning'
              | 'shower'
              | 'bath'
              | 'mountain'
              | 'balcony'
              | 'coffee'
              | 'fridge'
              | 'safe'
              | 'sofa'
              | 'room-service'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  virtualTourUrl?: string | null;
  isFeatured?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dining".
 */
export interface Dining {
  id: number;
  name: string;
  slug: string;
  type: 'outdoor' | 'indoor' | 'lounge' | 'poolside';
  cuisine?: string | null;
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  openingHours: string;
  capacity?: string | null;
  featuredImage?: (number | null) | Media;
  imageUrl?: string | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  menuPdf?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities".
 */
export interface Facility {
  id: number;
  name: string;
  slug: string;
  category: 'wellness' | 'recreation' | 'family' | 'services';
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  openingHours?: string | null;
  featuredImage?: (number | null) | Media;
  imageUrl?: string | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  isHighlight?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  name: string;
  slug: string;
  type: 'ballroom' | 'meeting-room' | 'wedding' | 'social';
  tagline?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  areaSize?: string | null;
  ceilingHeight?: string | null;
  capacityMax?: number | null;
  seatingLayouts?:
    | {
        style: 'theatre' | 'classroom' | 'banquet' | 'u-shape' | 'cocktail';
        capacity: number;
        id?: string | null;
      }[]
    | null;
  featuredImage?: (number | null) | Media;
  imageUrl?: string | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  brochurePdf?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers".
 */
export interface Offer {
  id: number;
  title: string;
  slug: string;
  category: 'stay' | 'dining' | 'adventure' | 'events' | 'meeting';
  categoryLabel?: string | null;
  discountBadge?: string | null;
  price?: string | null;
  validUntilText?: string | null;
  shortDescription?: string | null;
  inclusions?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  terms?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  imageUrl?: string | null;
  ctaType?: ('booking' | 'whatsapp' | 'rfp') | null;
  ctaLink?: string | null;
  ctaText?: string | null;
  order?: number | null;
  isActive?: boolean | null;
  promoCode?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries".
 */
export interface Gallery {
  id: number;
  title: string;
  slug?: string | null;
  category: 'rooms' | 'dining' | 'facilities' | 'events' | 'resort';
  image?: (number | null) | Media;
  imageUrl?: string | null;
  caption?: string | null;
  description?: string | null;
  isVirtualTour?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  category: 'news' | 'travel-guide' | 'wedding-tips' | 'culinary';
  excerpt?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  featuredImage?: (number | null) | Media;
  imageUrl?: string | null;
  readTime?: string | null;
  author?: string | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  bookingCode: string;
  guestName: string;
  guestEmail: string;
  guestPhone: string;
  guestIdentityNumber?: string | null;
  room: number | Room;
  checkIn: string;
  checkOut: string;
  guestsCount: number;
  totalAmount: number;
  status: 'pending' | 'paid' | 'cancelled' | 'expired';
  midtransTransactionId?: string | null;
  paymentMethod?: string | null;
  specialRequests?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  guestName: string;
  source: 'google' | 'tripadvisor' | 'ota' | 'direct';
  rating: number;
  stayDate?: string | null;
  comment: string;
  isPublished?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: number;
  name: string;
  slug: string;
  category: 'waterpark' | 'nature' | 'heritage' | 'culinary' | 'golf';
  categoryLabel?: string | null;
  distance?: string | null;
  travelTime?: string | null;
  tagline?: string | null;
  description?: string | null;
  imageUrl?: string | null;
  image?: (number | null) | Media;
  googleMapsUrl?: string | null;
  recommendedFor?: string | null;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'rooms';
        value: number | Room;
      } | null)
    | ({
        relationTo: 'dining';
        value: number | Dining;
      } | null)
    | ({
        relationTo: 'facilities';
        value: number | Facility;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'offers';
        value: number | Offer;
      } | null)
    | ({
        relationTo: 'galleries';
        value: number | Gallery;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'destinations';
        value: number | Destination;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  tagline?: T;
  description?: T;
  size?: T;
  bedType?: T;
  capacity?: T;
  order?: T;
  basePrice?: T;
  discountPrice?: T;
  featuredImage?: T;
  imageUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  amenities?:
    | T
    | {
        name?: T;
        icon?: T;
        id?: T;
      };
  virtualTourUrl?: T;
  isFeatured?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "dining_select".
 */
export interface DiningSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  cuisine?: T;
  tagline?: T;
  description?: T;
  openingHours?: T;
  capacity?: T;
  featuredImage?: T;
  imageUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  menuPdf?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "facilities_select".
 */
export interface FacilitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  tagline?: T;
  description?: T;
  openingHours?: T;
  featuredImage?: T;
  imageUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  isHighlight?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  tagline?: T;
  description?: T;
  areaSize?: T;
  ceilingHeight?: T;
  capacityMax?: T;
  seatingLayouts?:
    | T
    | {
        style?: T;
        capacity?: T;
        id?: T;
      };
  featuredImage?: T;
  imageUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  brochurePdf?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "offers_select".
 */
export interface OffersSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  categoryLabel?: T;
  discountBadge?: T;
  price?: T;
  validUntilText?: T;
  shortDescription?: T;
  inclusions?:
    | T
    | {
        item?: T;
        id?: T;
      };
  terms?:
    | T
    | {
        item?: T;
        id?: T;
      };
  description?: T;
  featuredImage?: T;
  imageUrl?: T;
  ctaType?: T;
  ctaLink?: T;
  ctaText?: T;
  order?: T;
  isActive?: T;
  promoCode?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "galleries_select".
 */
export interface GalleriesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  image?: T;
  imageUrl?: T;
  caption?: T;
  description?: T;
  isVirtualTour?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  category?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  imageUrl?: T;
  readTime?: T;
  author?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  bookingCode?: T;
  guestName?: T;
  guestEmail?: T;
  guestPhone?: T;
  guestIdentityNumber?: T;
  room?: T;
  checkIn?: T;
  checkOut?: T;
  guestsCount?: T;
  totalAmount?: T;
  status?: T;
  midtransTransactionId?: T;
  paymentMethod?: T;
  specialRequests?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  guestName?: T;
  source?: T;
  rating?: T;
  stayDate?: T;
  comment?: T;
  isPublished?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  category?: T;
  categoryLabel?: T;
  distance?: T;
  travelTime?: T;
  tagline?: T;
  description?: T;
  imageUrl?: T;
  image?: T;
  googleMapsUrl?: T;
  recommendedFor?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  hero?: {
    badge?: string | null;
    titleLine1?: string | null;
    titleAccent?: string | null;
    titleLine2?: string | null;
    subtitle?: string | null;
    backgroundImage?: (number | null) | Media;
    backgroundImageUrl?: string | null;
    exploreRoomsText?: string | null;
    virtualTourText?: string | null;
    features?:
      | {
          title: string;
          icon?: ('mountain' | 'calendar' | 'dining' | 'sparkle') | null;
          id?: string | null;
        }[]
      | null;
  };
  sections?: {
    roomsSubtitle?: string | null;
    roomsTitle?: string | null;
    roomsDesc?: string | null;
    diningSubtitle?: string | null;
    diningTitle?: string | null;
    diningDesc?: string | null;
    eventsSubtitle?: string | null;
    eventsTitle?: string | null;
    eventsDesc?: string | null;
  };
  subpageBanners?: {
    roomsBannerUrl?: string | null;
    diningBannerUrl?: string | null;
    eventsBannerUrl?: string | null;
    facilitiesBannerUrl?: string | null;
    virtualTourBannerUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  hotelName: string;
  tagline?: string | null;
  phone: string;
  whatsapp: string;
  email: string;
  address?: string | null;
  googleMapsUrl?: string | null;
  socialMedia?: {
    instagram?: string | null;
    facebook?: string | null;
    tiktok?: string | null;
  };
  logo?: (number | null) | Media;
  logoWhite?: (number | null) | Media;
  bookingConfig?: {
    /**
     * Pilih sistem reservasi yang aktif saat tamu mengklik tombol Pesan Kamar atau Cek Ketersediaan.
     */
    engineType?: ('third-party' | 'internal' | 'whatsapp') | null;
    /**
     * Tautan resmi sistem booking engine (misal: DIP Booking Engine dengan keyid hotel).
     */
    thirdPartyUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-config".
 */
export interface HeaderConfig {
  id: number;
  navItems?:
    | {
        label: string;
        href: string;
        subItems?:
          | {
              label: string;
              href: string;
              description?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  bookButtonText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-config".
 */
export interface FooterConfig {
  id: number;
  aboutText?: string | null;
  copyrightText?: string | null;
  quickLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popups".
 */
export interface Popup {
  id: number;
  isEnabled?: boolean | null;
  title?: string | null;
  content?: string | null;
  image?: (number | null) | Media;
  buttonText?: string | null;
  buttonLink?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        badge?: T;
        titleLine1?: T;
        titleAccent?: T;
        titleLine2?: T;
        subtitle?: T;
        backgroundImage?: T;
        backgroundImageUrl?: T;
        exploreRoomsText?: T;
        virtualTourText?: T;
        features?:
          | T
          | {
              title?: T;
              icon?: T;
              id?: T;
            };
      };
  sections?:
    | T
    | {
        roomsSubtitle?: T;
        roomsTitle?: T;
        roomsDesc?: T;
        diningSubtitle?: T;
        diningTitle?: T;
        diningDesc?: T;
        eventsSubtitle?: T;
        eventsTitle?: T;
        eventsDesc?: T;
      };
  subpageBanners?:
    | T
    | {
        roomsBannerUrl?: T;
        diningBannerUrl?: T;
        eventsBannerUrl?: T;
        facilitiesBannerUrl?: T;
        virtualTourBannerUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  hotelName?: T;
  tagline?: T;
  phone?: T;
  whatsapp?: T;
  email?: T;
  address?: T;
  googleMapsUrl?: T;
  socialMedia?:
    | T
    | {
        instagram?: T;
        facebook?: T;
        tiktok?: T;
      };
  logo?: T;
  logoWhite?: T;
  bookingConfig?:
    | T
    | {
        engineType?: T;
        thirdPartyUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-config_select".
 */
export interface HeaderConfigSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        label?: T;
        href?: T;
        subItems?:
          | T
          | {
              label?: T;
              href?: T;
              description?: T;
              id?: T;
            };
        id?: T;
      };
  bookButtonText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer-config_select".
 */
export interface FooterConfigSelect<T extends boolean = true> {
  aboutText?: T;
  copyrightText?: T;
  quickLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popups_select".
 */
export interface PopupsSelect<T extends boolean = true> {
  isEnabled?: T;
  title?: T;
  content?: T;
  image?: T;
  buttonText?: T;
  buttonLink?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}